### ISSUE TITLE
Undefined message

### ISSUE THREAD

**Issue by kerkenit** [athombv/nl.buienradar#9]
I'm getting the following message on the app page:

Stack trace:

TypeError: Cannot read property 'split' of undefined
at Request._callback (/app.js:244:51)
at Request.self.callback (/node_modules/request/request.js:197:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/node_modules/request/request.js:1050:14)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:996:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)

**Comment by BasKiers** [comment]
fixed as of v2.0.x
